language: bash
services: docker
before_install:
    - cd /
    - echo "Estamos na pasta do docker!"
script:
    - docker-compose build
before_deploy:
    - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
    provider: script
    script:
        docker push suleimanmoaraes/rest-with-spring-boot-udemy;
        docker push suleimanmoaraes/mysql-rest-with-spring-boot-udemy;
    on:
        branch: master
notifications:
    email: false