version: '3.4'
services:
        db:
                image: suleimanmoaraes/mysql-rest-with-spring-boot-udemy
                command: mysqld --default-authentication-plugin=mysql_native_password
                restart: always
                build: 
                        context: .
                        dockerfile: Dockerfile
                environment:
                        TZ: America/Sao_Paulo
                        MYSQL_ROOT_PASSWORD: senha
                        MYSQL_USER: usuario
                        MYSQL_PASSWORD: senha
                        MYSQL_DATABASE: rest_with_spring_boot_udemy
                ports:
                        - "3308:3306"
                networks:
                        - udemy-network
        rest-with-spring-boot-udemy:
                image: suleimanmoaraes/rest-with-spring-boot-udemy
                restart: always
                build: ./api
                working_dir: /api
                environment:
                        TZ: America/Sao_Paulo
                        SPRING_BOOT_ENVIRONMENT: Production
                        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false
                        SPRING_DATASOURCE_PASSWORD: senha
                volumes:
                        - ./api:/api
                        - ~/.m:/root/.m2
                ports: 
                        - "8080:8080"
                command: mvn clean spring-boot:run
                links: 
                        - db
                depends_on:
                        - db
                networks:
                        - udemy-network
networks:
                udemy-network:
                        driver: bridge